# THESE ARE TOOLS RELATED FOR THE APP UNLIKE EACH SERVICES, THESE TOOLS WILL RELY ON THIS DOCKER-COMPOSE.TOOLS.YML

services:
  redisinsight:
    # redis/redisinsight:2.70
    image: redis/redisinsight@sha256:ed94a0eb2a00ab6923ba71560d2b24dadee7d1493e190d8daf113b860e6271af
    container_name: redisinsight
    env_file:
      - .env
    environment:  # AUTO CONNECT TO THE SERVICES/REDIS DATABASE
      - RI_REDIS_HOST=${COMPOSE_REDIS_HOST:-redisstack}
      - RI_REDIS_PORT=${COMPOSE_REDIS_EXPOSE_PORT:-6379}
      - RI_REDIS_PASSWORD=${COMPOSE_REDIS_PASSWORD:-admin}
    ports:
      - "${COMPOSE_REDISINSIGHT_EXPOSE_PORT:-5540}:5540"
    volumes:
      - redisinsight_data:/data


volumes:
  redisinsight_data:

