# THESE ARE TOOLS RELATED FOR THE APP UNLIKE EACH SERVICES, THESE TOOLS WILL RELY ON THIS DOCKER-COMPOSE.TOOLS.YML

services:
# might remove on deploy
  pgadmin:
    # dpage/pgadmin4:snapshot
    image: dpage/pgadmin4@sha256:e3391fbf625360136995800377968d0cfaf0a6277d76d651b355f4eeac9c67a3
    container_name: pgadmin
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${SERVER_PGADMIN_EMAIL:-admin@example}
      - PGADMIN_DEFAULT_PASSWORD=${SERVER_PGADMIN_PASSWORD:-admin}
    ports:
      # pgAdmin by default listen to 80 so use 80 and expose outside as 8080
      - "${COMPOSE_PGADMIN_EXPOSE_PORT:-8080}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    # restart: unless-stopped

  redisinsight:
    # redis/redisinsight:2.70
    image: redis/redisinsight@sha256:ed94a0eb2a00ab6923ba71560d2b24dadee7d1493e190d8daf113b860e6271af
    container_name: redisinsight
    env_file:
      - .env
    environment:  # AUTO CONNECT TO THE SERVICES/REDIS DATABASE
      - RI_REDIS_HOST=${COMPOSE_REDIS_HOST:-redisstack}
      - RI_REDIS_PORT=${COMPOSE_REDIS_EXPOSE_PORT:-6379}
      - RI_REDIS_PASSWORD=${COMPOSE_REDIS_PASSWORD:-admin}
    ports:
      - "${COMPOSE_REDISINSIGHT_EXPOSE_PORT:-5540}:5540"
    volumes:
      - redisinsight_data:/data


volumes:
  pgadmin_data:
  redisinsight_data:

